/* Inlcude all H2Lib moduls */

#ifdef __cplusplus
extern "C" { 
#endif

#include "Library/aca.h"
#include "Library/amatrix.h"
#include "Library/avector.h"
#include "Library/basic.h"
#include "Library/bem2d.h"
#include "Library/bem3d.h"
#include "Library/blas.h"
#include "Library/block.h"
#include "Library/clsettings.h"
#include "Library/cluster.h"
#include "Library/clusterbasis.h"
#include "Library/clustergeometry.h"
#include "Library/clusteroperator.h"
#include "Library/curve2d.h"
#include "Library/dblock.h"
#include "Library/dcluster.h"
#include "Library/dclusterbasis.h"
#include "Library/dclusteroperator.h"
#include "Library/ddcluster.h"
#include "Library/dh2compression.h"
#include "Library/dh2matrix.h"
#include "Library/duniform.h"
#include "Library/eigensolvers.h"
#include "Library/factorizations.h"
#include "Library/gaussquad.h"
#include "Library/h2arith.h"
#include "Library/h2compression.h"
#include "Library/h2matrix.h"
#include "Library/h2update.h"
#include "Library/harith.h"
#include "Library/harith2.h"
#include "Library/hcoarsen.h"
#include "Library/helmholtzbem3d.h"
#include "Library/helmholtzoclbem3d.h"
#include "Library/hmatrix.h"
#include "Library/krylov.h"
#include "Library/krylovsolvers.h"
#include "Library/laplacebem2d.h"
#include "Library/laplacebem3d.h"
#include "Library/macrosurface3d.h"
#include "Library/matrixnorms.h"
#include "Library/oclbem3d.h"
#include "Library/opencl.h"
#include "Library/parameters.h"
#include "Library/realavector.h"
#include "Library/rkmatrix.h"
#include "Library/settings.h"
#include "Library/simd_avx.h"
#include "Library/simd_sse2.h"
#include "Library/simd.h"
#include "Library/singquad1d.h"
#include "Library/singquad2d.h"
#include "Library/sparsematrix.h"
#include "Library/sparsepattern.h"
#include "Library/surface3d.h"
#include "Library/tet3d.h"
#include "Library/tet3dp1.h"
#include "Library/tet3drt0.h"
#include "Library/tri2d.h"
#include "Library/tri2dp1.h"
#include "Library/tri2drt0.h"
#include "Library/truncation.h"
#include "Library/uniform.h"
#include "Library/visualize.h"

#ifdef __cplusplus 
}
#endif
